services:
  truetea1:
    container_name: truetea1
    image: postgres:latest
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 500M
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: truetea1
    ports:
      - 5468:5432